### ISSUE TITLE
Setting Froala license keys - getting unlicensed error

### ISSUE THREAD

**Issue by adamgins** [froala/froala-reactive#11]
@rjsmith wondering if you have an example of doing this... I am having some issues. @stefanneculai has been helping

See https://github.com/froala/meteor-froala/issues/9#issuecomment-71924916

 but as you authored this package, thought I ask you to, so just wondering if you had an example,

my code looks like:

```
{{> froalaReactive  _onblur=doSave _value=myDoc.content buttons=froalaTextButtons theme=froalaTheme initOnCLick=true alwaysVisible=true inlineMode=true toolbarFixed=true plainPaste=true key=getActivationKey}}
```
 Then I have a helper function 'Template.SOME_TEMPLATE.helpers`:
```
 getActivationKey: function () {
      return 'MYLONGKEY';
    },
```

Ah. I should add the I am running on Nitrous. I have added the keys to the Froala license for `*.nitrousbox.com`

**Comment by rjsmith** [comment]
Hi,

Sorry .. I am still working on my project locally, and I am some way off needing to purchase a license .. you are ahead of me!   I can't provide any support for Froala Editor itself, Froala-Reactive is really a pretty thin wrapper around it (take a look at [its code](https://github.com/froala/froala-reactive/blob/master/froala-reactive.js) to see how little it actually does).

**Comment by rjsmith** [comment]
Hi @adamgins ,

Well, I finally just reached the point where I needed to deploy my project with a licensed Froala Editor.  I got the license key to work by passing it into the froalaReactive inclusion template , specifying the 'key' attribute.  Because I did not want to repeat the key argument on every FE instance in my app, I have created a simple wrapper local package that has this html template:

```html
<template name='editableHTML'>
  <div class="editable-html" data-toggle='tooltip' title='Click to edit and select contents for more options'>
    {{> froalaReactive extendContextWithKey}}
    <span class="editable-overlay"><i class="fa fa-pencil"></i></span>
  </div>
</template>
```

and this as the template helper code:

```javascript
Template.editableHTML.helpers({
  extendContextWithKey: function () {
    var self = this;
    self.key = Meteor.settings.public.froalaKey;
    return self;
  }
})
```

And then I refer to {{> editableHTML _value=blah initOnClick=true .... }} in my application templates.

It seems to work OK.  I stored the key in a settings.json file and accessed it via a helper that returned the value of `Meteor.settings.public.froalaKey`

**Comment by adamgins** [comment]
Thanks. I did something similar but set at global level.. may have to go back and look at it, it's been a while. 

Anyway, I had created an array too for all the domains and keys as I had multiple test systems running on different domains.
