### ISSUE TITLE
Can't apply custom themes

### ISSUE THREAD

**Issue by EddyBorja** [froala/froala-reactive#17]
For some reason setting the 'theme' attribute for the froala editor isn't applying any themes. My editor is also using a white background that makes it hard to see the buttons. Any idea what could be wrong?

**Comment by rjsmith** [comment]
Hi. Can you post an example of the {{> froalaReactive }} tag you are using? How are you specifying the 'theme' attribute?

**Comment by EddyBorja** [comment]
My templates use Jade syntax, but these are the only options I'm passing in:
+froalaReactive(_onBeforeSave=doSave theme='dark' inlineMode=false toolbarFixed=false _value=this.description)

**Comment by rjsmith** [comment]
Have you included the additional CSS files?

https://www.froala.com/wysiwyg-editor/docs/examples/color-themes

**Comment by EddyBorja** [comment]
I had tried loading my own custom theme first and it didn't work. Will froalaReactive be able to find the files anywhere we place them?

**Comment by rjsmith** [comment]
Hi,
Froala reactive is just a thin wrapper around the Froala editor JS itself, and doesn't have any additional css - handling code. Thus, I suspect your issue is to do with meteor's general CSS handling , and /or how that interacts with Froala editor.  if you use your browsers inspection tool on an instance of the FE editor in your app, can you see if the theme css appears to be loaded? 
FYI .. I haven't used a custom theme myself, so don't have any specific experience with this with which I can help you with.

**Comment by EddyBorja** [comment]
Found the problem, I didn't realize the custom theme tags in the css needed "-theme" appended to the actual theme name that gets passed in. It turns out Froala uses a white background by default and the editor's buttons must be getting affected by some other css I have that makes my links white.
