### ISSUE TITLE
Multiple Forms in one Template and other questions

### ISSUE THREAD

**Issue by FinnFrotscher** [froala/froala-reactive#28]
Hi, 
Thanks for this awesome editor!
 

- I  want to use this editor to provide a form with 4 fields that lets users add` title`, `description`, `another description` and lets them chose an item from a `dropdown list`. 
I want to give them the same form twice, once without data (when they wont to add a new entry) and once with predefined data (when they want to edit an existing entry) 
How to do this? The documentation does not explain. 
specifically: how to start a form without data? with multiple fields? and a fixed hight?

- And how to make this little `'fr-quick-insert' `popup stay a little longer. I cant grab it, its too quick. 

- and in general. when the official docs say: [link](https://www.froala.com/wysiwyg-editor/docs/examples/predefined-height)

HTML
```
<div id="froala-editor">
  <p>Set a specific height to the WYSIWYG HTML editor using the <a href="../options#height" title="height option" target="_blank">height</a> option. If the text inside is longer, then the rich text editor will get a vertical scrollbar.</p>
</div>
```
JAVASCRIPT
```
<script>
  $(function() {
    $('div#froala-editor').froalaEditor({
      height: 300
    })
  });
</script>
```
how would i translate this into meteor?

**Comment by rjsmith** [comment]
Hi,

The froala-reactive is a simple wrapper over the actual FE editor, providing some basic reactivity integration with the Meteor framework.

1. I think this is a wider question about how to use Meteor, rather than a specific issue with this package.  I suggest you start with some of the excellent tutorials out there. The Discover Meteor book is well worth purchasing too.  You may also want to check out the [donchess:autoform-froala](https://atmospherejs.com/donchess/autoform-froala) package. That is an alternative wrapper package to this one. Never used it myself, but might help you with integrating with the autoform package eco-system, which makes form handling in Meteor very easy.

2. I have seen this behaviour also. I have disabled the quick insert plugin in my own application for now. I think this is a core issue with FE rather than this wrapper package.

3. Did you follow the README for this package? You can set any of the [FE options](https://www.froala.com/wysiwyg-editor/docs/options) when you initialise the template.
e.g:
```html
<template name="myTemplate">
{{> froalaReactive getFEContext}}
</template>
```

```javascript
Template.myTemplate.helpers(function () {
  getFEContext: function () {
    return {
      height: 300
    }
  });
```

**Comment by rjsmith** [comment]
Closing
